# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

ZSH_THEME="jetprose"

DISABLE_AUTO_UPDATE="false"
COMPLETION_WAITING_DOTS="true"

plugins=(git virtualenvwrapper python vagrant django)

source $ZSH/oh-my-zsh.sh

export ANDROID_HOME=/home/jetmind/tools/android-sdk-linux
export PATH=/home/jetmind/sml/bin:/home/jetmind/bin:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
export PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
export PATH=$PATH:$HOME/gears/mozart2-2.0.0-alpha.0+build.3777.62f3ec5-x86_64-linux/bin  # Oz

export EDITOR=vim

export GOPATH=$HOME/p/go
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$HOME/gears/sbt/bin

# aliases
alias zshconfig="vim ~/.zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"
alias o="xdg-open"

alias git="nocorrect git"
alias sudo="nocorrect sudo"
alias workon="nocorrect workon"
alias g="git"
alias w="workon"
alias g="ack-grep"

alias t="python ~/tasks/t/t.py --task-dir ~/tasks --list tasks"

# options
export SPROMPT="Correct $fg[red]%R$reset_color to $fg[green]%r?$reset_color (Yes, No, Abort, Edit) "
setopt auto_cd
setopt extended_glob
autoload -U zmv

# autojump
[[ -s ~/.autojump/etc/profile.d/autojump.zsh ]] && source ~/.autojump/etc/profile.d/autojump.zsh
export AUTOJUMP_KEEP_SYMLINKS=1
# needed for zsh autojump completion
autoload -U compinit; compinit

# pythonbrew
# [[ -s $HOME/.pythonbrew/etc/bashrc ]] && source $HOME/.pythonbrew/etc/bashrc

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
